collect/urls.py
from django.urls import path
from . import views
from . import api_view

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    #path('collect/<pk>', views.Detail.as_view(), name='detail'),
    path('collect/<pk>', views.detail, name='detail'),
    path('update/<pk>', views.update, name='update'),
    path('post/', views.add_post, name='post'),
    path('example/', views.ExampleList.as_view(), name='example'),
    path('collection/<username>', views.CollectList.as_view(), name='list'),
    #path('wish', views.WishList.as_view(), name='wish'),
    #path('collection/<username>/wish', views.UserWish.as_view(), name='user_wish'),
    path('category', views.CategoryList.as_view(), name='category'),
    #path('collection/<username>/category', views.UserCategory.as_view(), name='user_category'),
    path('place', views.PlaceList.as_view(), name='place'),
    path('nice', views.NiceList.as_view(), name='nice'),
    path('nice/<collect_pk>', views.NiceUser.as_view(), name='nicer'),
    path('download', views.download_page, name='download_page'),
    path('downloading', views.download, name='download'),
    path('search/', views.search, name='search'),
    # API
    path('category/api', api_view.CategoryAPI.as_view(), name='cat_api'),
    path('category/api/<pk>', api_view.CategoryRetAPI.as_view(), name='cat_api_pk'),
    path('place/api', api_view.PlaceAPI.as_view(), name='place_api'),
    path('place/api/<pk>', api_view.PlaceRetAPI.as_view(), name='place_api_pk'),
    path('post/api', api_view.CollectAPI.as_view(), name='post_api'),
    path('collect/api/<pk>', api_view.CollectRetAPI.as_view(), name='collect_api_pk'),
    path('photo/api', api_view.PhotoAPI.as_view(), name='photo_api'),
    path('collect/<collect_pk>/comment', api_view.CommentAPI.as_view(), name='collect_api'),
    path('collect/<comment_pk>/reply', api_view.ReplyAPI.as_view(), name='reply_api'),
    path('collect/<collect_pk>/nice', api_view.NiceAPI.as_view(), name='nice_api'),
    path('offer/<collect_pk>/', api_view.OfferAPI.as_view(), name='offer_api'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('collect.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('user/', include('user.urls', namespace='user')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import (PasswordReset,
                    PasswordResetDone,
                    PasswordResetConfirm,
                    PasswordResetComplete,
                    UserCreate,
                    UserCreateDone,
                    UserCreateComplete,
                    profile,
                    detail,
                    delete,
                    delete_conf,
                    )
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html',
        next_page='/'), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('delete/<username>', delete, name='user_delete'),
    path('delete/confirm/<username>', delete_conf, name='delete_conf'),
    path('register/', UserCreate.as_view(), name='register'),
    path('register/done/', UserCreateDone.as_view(), name='register_done'),
    path('register/complete/<token>/', UserCreateComplete.as_view(), name='register_complete'),
    path('password/reset/', PasswordReset.as_view(), name='reset'),
    path('password/reset/done/', PasswordResetDone.as_view(), name='reset_done'),
    path('password/reset/confirm/<str:uidb64>/<str:token>/', PasswordResetConfirm.as_view(), name='reset_confirm'),
    path('password/reset/complete/', PasswordResetComplete.as_view(), name='reset_complete'),
    path('profile/', profile, name='profile'),
]

collect/models.py
from django.db import models
from django.utils import timezone
from PIL import Image
import uuid
from django.utils.translation import ugettext_lazy as _
from datetime import date
from user.models import User

class Tag(models.Model):
    class Text(models.TextChoices):
        Book = 'books', _("Books")
        Movie = 'moovie', _('Movie/Music')
        Electronics = 'ele', _('Electronics')
        PC = 'pc', _('PC')
        Drink = 'drink', _('Drink/Grocery')
        Interior = 'inte', _('Interior/Novelty')
        Commodity = 'commo', _('Commodities')
        Handmade = 'hand', _('Handmade')
        Hobby = 'hobby', _('Hobby/Toy')
        Clothes = 'clo', _('Clothes/Shoes/Bag')
        Car = 'car', _('Car/Bike')
        Sports = 'sports', _('Sports/Outdoors')
    text = models.CharField(_('Tag'), max_length=30, choices=Text.choices, blank=True, null=True)

    def __str__(self):
        return self.text

class Category(models.Model):
    name = models.CharField(_('category'), max_length=24)
    made = models.DateTimeField(_('date of made'), default=timezone.now)
    user = models.ForeignKey(User, verbose_name='user', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Place(models.Model):
    name = models.CharField(_('place'), max_length=24)
    made = models.DateTimeField(_('date of made'), default=timezone.now)
    user = models.ForeignKey(User, verbose_name='user', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Collect(models.Model):
    id = models.SlugField(primary_key=True, editable=False)
    name = models.CharField(_('name'), max_length=24)
    product_name = models.CharField(_('product name'), max_length=32, blank=True, null=True)
    maker = models.CharField(_('maker name'), max_length=32, blank=True, null=True)
    num = models.PositiveIntegerField(_('number'), blank=True, null=True, default=1)
    saved = models.CharField(_('saved state'), max_length=36, blank=True, null=True)
    explain = models.TextField(_('explain'), blank=True, null=True)
    acq_day = models.DateField(_('day of acquisition'), blank=True, null=True)
    acq_place = models.CharField(_('place of acquisition'), max_length=36, blank=True, null=True)
    posted = models.DateTimeField(_('posted date'), default=timezone.now)
    user = models.ForeignKey(User, verbose_name='user', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, verbose_name=_('category'), blank=True, null=True, on_delete=models.SET_NULL)
    place = models.ForeignKey(Place, verbose_name=_('place'),blank=True, null=True, on_delete=models.SET_NULL)
    price = models.PositiveIntegerField(_('Price'), blank=True, null=True)
    nice_num = models.PositiveIntegerField(_('Nice'), default=0)
    public = models.BooleanField(_('public'), max_length=10, default=False)
    class State(models.TextChoices):
        NEGOTIABLE = "NEGOTIABLE", _("Negotiable")
        NONNEGOTIABLE = "NON-NEGOTIABLE", _("Non-negotiable")
        LOOKFORBUYER = "WANT-SELL", _("Looking for buyers")
        THIRSTING = "THIRSTY", _("Thirsting")
    state = models.CharField(_('state'), max_length=15, choices=State.choices, default='NON-NEGOTIABLE')
    tag = models.ManyToManyField(Tag, verbose_name='tag', blank=True)

    def __str__(self):
        return self.name

    def nice_count(self):
        return Nice.objects.filter(collect=self).count()

    def com_count(self):
        return Comment.objects.filter(collect=self).count()


class Photo(models.Model):
    photo = models.ImageField(_('picture'), upload_to='collect/', blank=True, null=True)
    collect = models.ForeignKey(Collect, verbose_name='collect', on_delete=models.CASCADE)

class Comment(models.Model):
    content = models.TextField(_('content'), max_length=400)
    collect = models.ForeignKey(Collect, verbose_name='collect', on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name='user', on_delete=models.CASCADE)
    posted = models.DateTimeField(_('posted date'), default=timezone.now)

class Reply(models.Model):
    content = models.TextField(_('content'), max_length=400)
    comment = models.ForeignKey(Comment, verbose_name='comment', on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name='user', on_delete=models.CASCADE)
    posted = models.DateTimeField(_('posted date'), default=timezone.now)

class Nice(models.Model):
    collect = models.ForeignKey(Collect, on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name='user', on_delete=models.CASCADE)
    posted = models.DateTimeField(_('date'), default=timezone.now)

class Offer(models.Model):
    target_col = models.ForeignKey(Collect, related_name="tar", on_delete=models.CASCADE)
    rec_col = models.ForeignKey(Collect, on_delete=models.CASCADE)
    posted = models.DateTimeField(_('date'), default=timezone.now)

collect/forms.py
from .models import Collect, Category, Place, Photo, Tag
from django import forms
from user.models import User
from django.utils.translation import ugettext as _

class PostForm(forms.ModelForm):
    name = forms.CharField(help_text="***",
        widget=forms.TextInput(
            attrs={'placeholder': 'Collection title'}
        )
    )
    acq_day = forms.DateField(
        widget=forms.DateInput(attrs={"type":"date"}),
        required = False
    )
    price = forms.IntegerField(
        widget=forms.TextInput(attrs={"type": "text"}),
        required=False
    )

    class Meta:
        model = Collect
        fields = [
        'name', 'product_name', 'maker', 'num', 'acq_day','acq_place', 'price',
        'acq_day', 'state', 'category', 'place', 'saved', 'public', 'explain'
        ]

        """   ラジオボタン
        widgets = {
            'state': forms.RadioSelect(),
        }
        """

    def __init__(self, user, *args, **kwargs):
        #author = self.request.user
        #slug = ''.join(random.choice(string.ascii_letters + string.digits + kigou) for _ in range(8))
        super().__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.filter(user=user)
        self.fields['place'].queryset = Place.objects.filter(user=user)


class ImageForm(forms.ModelForm):
    photo = forms.ImageField(label='Image')
    class Meta:
        models = Photo
        fields = ('photo', 'collect')

"""
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        
class PlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = '__all__'
"""

collect/templates/collect/category.html
{% extends 'collect/base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{% trans "Category" %}{% endblock %}
{% block content %}
<section class="pbBottom">
    <div class="columnArea">
        <h3 class="Midashi">{{ theme }}</h3>
          {% for category in categories %}
            <div class="category_part mt5 mb5 pack_{{category.pk }}" id="{{ category.name }}">
                <div class="dropdown pt5 pb5 flex-normal pr10 pl10" id="category_{{ category.pk }}">
                    <div class="cat_title brAll flex1"><h4>{{ category.name }}</h4></div>
                    <div class="mla mta mba">
                      <div class="w60px countsZ">
                        <h4>{{ category.collect_set.count }}</h4>
                      </div>
                    </div>
                </div>
              <div class="w120px flex-normal">
                <div class="pl5 w50 pr5">
                  <div id="nameChaBtn_{{ category.pk }}" class="submitB pt3 pb3 nameChaBtn flex-cen w100 h100">
                    <a>ℵ</a>
                  </div>
                </div>
                <div class="pl5 w50 pr5">
                  <div id="delOpenBtn_{{ category.pk }}" class="submitB pt3 pb3 delOpenBtn flex-cen w100 h100">
                    <a>-</a>
                  </div>
                </div>
              </div>
            </div>
            <div class="nameChaZone_{{ category.pk }} cat_add pb5 pt3 flex-normal mb15 mt5 off">
              <input type="text" class="flex1" id="cat_name_{{ category.pk }}" maxlength="24" placeholder="Category name">
              <div class="pr5 pl5 w120px">
                <span id="cat_btn_{{ category.pk }}" class="NCB submitB w100 h100 flex-cen">Change</span>
              </div>
            </div>
            {% if category.collect_set.count != 0 %}
            <div class="List category_{{ category.pk }} off" style="width: 100%;">
              {% for collect in category.collect_set.all %}
                <article class="collectList hrefBox category_col_{{ category.pk }}{% for tag in collect.tag.all %} {{ tag.text }}_arti{% endfor %} {{ collect.state }}_arti">
                  <div class="imageFrame">
                    {% if collect.photo_set %}
                      <img src="{{ collect.photo_set.first.photo.url }}">
                    {% endif %}
                  </div>
                  <div class="collectinfo">
                    <div class="ue">
                        <div class="itemName">
                          <h3>{{ collect.name }}</h3>
                        </div>
                        <div class="itemVisual">
                            {% if collect.state == "NEGOTIABLE" %}
                              <a class="circleV"></a>
                            {% elif collect.state == "THIRSTY" %}
                              <a class="starV">★</a>
                            {% elif collect.state == "NON-NEGOTIABLE" %}
                              <a class="heartV">♥</a>
                            {% else %}
                              <a class="squareV"></a>
                            {% endif %}
                          <div class="itemPrice">
                            <a class="priceV">
                              {% if collect.price %}
                                {{ collect.price }}
                              {% endif %}
                            </a>
                          </div>
                        </div>
                    </div>
                    <div class="shita">
                      <div class="hosokuA">
                        <div class="sonotaA">
                          {% if collect.niced %}
                            <i class="far fa-thumbs-up mr15 salmon"></i>
                          {% else %}
                            <i class="far fa-thumbs-up mr15"></i>
                          {% endif %}
                          <span>
                            {{ collect.nice_count }}
                          </span>
                          <i class="far fa-comments mr15 ml20"></i>
                          <span>
                            {{ collect.com_count }}
                          </span>
                        </div>
                        <div class="sonotaA">
                          <span>{{ collect.posted }}</span>
                        </div>
                      </div>
                      <div class="placeArea">
                        <a class="placeInfo">
                          {% if collect.place %}
                            {{ collect.place }}
                          {% endif %}
                        </a>
                      </div>
                    </div>
                  </div>
                  <a class="hrefBoxIn" href="{% url 'detail' collect.id %}"></a>
                </article>
              {% endfor %}
            </div>
          {% endif %}
            <div class="modal off" id="delZone_{{ category.pk }}"></div>
            <div class="modal-con off" id="delZone_{{ category.pk }}_con">
              <div>
                <h3 style="text-align: center;">Delete {{ category.name }}?</h3>
                <h4 style="text-align: center;">*{% trans "contents is not deleted" %}</h4>
              </div>
              <div class="mt25 flex-normal">
                <a style="height: 50px" class="cancelBtn flex-cen w50 h50px"><b>{% trans "Cancel" %}</b></a>
                <a id="catDelBtn_{{ category.pk }}" class="submitC categoryDelBtn flex-cen w50 h50px"><b>{% trans "Delete" %}</b></a>
              </div>
            </div>
          {% endfor %}
        <div class="category_part mt5 mb5 NCA">
          <div class="dropdown pb5 pt5 flex-normal pr10 pl10" id="no_category">
            <div class="cat_title brAll flex1">
              <h4 class="cat_title">{% trans "No category" %}</h4>
            </div>
            <div class="mla mta mba">
              <div class="w60px countsZ">
                <h4 class="no_no">{{ no_cats.count }}</h4>
              </div>
            </div>
          </div>
        </div>
      {% if no_cats.count != 0 %}
        <div class="List no_category off">
          {% for collect in no_cats %}
          <article class="collectList hrefBox no_cats{% for tag in collect.tag.all %} {{ tag.text }}_arti{% endfor %} {{ collect.state }}_arti">
            <div class="imageFrame">
              {% if collect.photo_set %}
                <img src="{{ collect.photo_set.first.photo.url }}">
              {% endif %}
            </div>
            <div class="collectinfo">
              <div class="ue">
                  <div class="itemName">
                    <h3>{{ collect.name }}</h3>
                  </div>
                  <div class="itemVisual">
                      {% if collect.state == "NEGOTIABLE" %}
                        <a class="circleV"></a>
                      {% elif collect.state == "THIRSTY" %}
                        <a class="starV">★</a>
                      {% elif collect.state == "NON-NEGOTIABLE" %}
                        <a class="heartV">♥</a>
                      {% else %}
                        <a class="squareV"></a>
                      {% endif %}
                    <div class="itemPrice">
                      <a class="priceV">
                        {% if collect.price %}
                          {{ collect.price }}
                        {% endif %}
                      </a>
                    </div>
                  </div>
              </div>
              <div class="shita">
                <div class="hosokuA">
                  <div class="sonotaA">
                    {% if collect.niced %}
                      <i class="far fa-thumbs-up mr15 salmon"></i>
                    {% else %}
                      <i class="far fa-thumbs-up mr15"></i>
                    {% endif %}
                    <span>
                      {{ collect.nice_count }}
                    </span>
                    <i class="far fa-comments mr15 ml20"></i>
                    <span>
                      {{ collect.com_count }}
                    </span>
                  </div>
                  <div class="sonotaA">
                    <span>{{ collect.posted }}</span>
                  </div>
                </div>
                <div class="placeArea">
                  <a class="placeInfo">
                    {% if collect.place %}
                      {{ collect.place }}
                    {% endif %}
                  </a>
                </div>
              </div>
            </div>
            <a class="hrefBoxIn" href="{% url 'detail' collect.id %}"></a>
          </article>
          {% endfor %}
        </div>
      {% endif %}
      <div class="list_add mt20 pb3 flex-normal" id="cat_post1">
        <input type="text" id="cat_name" maxlength="24" class="flex1" placeholder="New category">
        <div class="pr5 pl5 w120px">
          <span id="cat_button" class="w100 submitB pt3 pb3">{% trans "Add" %}</span>
        </div>
      </div>
    </div>
</section>
{% endblock %}
{% block js %}
<script src="{% static 'collect/attribute.js' %}"></script>
<script>
$(function(){
  $("div .SC_cat").addClass("active");
});
</script>
{% endblock %}

collect/templates/collect/post.html
{% extends 'collect/base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<div class="formArea">
  <h3>{{ tytle }}</h3>
  <form method="post" action="" enctype="multipart/form-data" class="mt10">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="field">
      <label for="id_name">{% trans "Name" %}:</label>
      <span class="helptext">{{ form.name.help_text }}</span>
      {{ form.name }}
      {% if form.name.errors %}
        {{ form.name.error }}
      {% endif %}
    </div>
    <div class="field">
      {{ form.product_name.label_tag }}
      {{ form.product_name }}
    </div>
    <div class="field">
      {{ form.num.label_tag }}
      {{ form.num }}
    </div>
    <div class="field">
      {{ form.category.label_tag }}<br>
      {{ form.category }}<span id="new_cat" class="sw_new w10 mla submitB">+</span>
      
      <div class="cat_add pt5 pb3 off" id="cat_post1">
          <input type="text" id="cat_name" placeholder="New category">
          <span id="cat_button" class="w10 mla submitB">Add</span>
      </div>
    
    </div>
    <div class="field">
      {{ form.place.label_tag }}
      <span class="helptext color_Blue">{% trans "Only you can see" %}</span>
      {{ form.place }}<span id="new_place" class="sw_new w10 mla submitB">+</span>

      <div class="place_add pt5 pb3 off" id="place_post1">
        <input type="text" id="place_name" placeholder="New place">
        <span id="place_button" class="w10 mla submitB">{% trans "Add" %}</span>
      </div>
    </div>
    <div class="field">
      {{ form.state.label_tag }}
      {{ form.state }}
    </div>
    <div class="field">
      {{ form.public.label_tag }}
      {{ form.public }}
    </div>
    <div class="field">
      <label>{% trans "Tag" %}:</label><span class="helptext color_Blue">{% trans "At most 3" %}</span><br>
      <div class="tag_select" id="id_tag">
        {% for tag in tags %}
          {% if tag in init_tags %}
            <input id="tag_{{ tag }}" name="post_tag" value="{{ tag }}" type="checkbox" checked>
            <label for="tag_{{ tag }}">{{ tag.label }}</label>
          {% else %}
            <input id="tag_{{ tag }}" name="post_tag" value="{{ tag }}" type="checkbox">
            <label for="tag_{{ tag }}">{{ tag.label }}</label>
          {% endif %}
        {% endfor %}
      </div>
    </div>
    <!-- 画像 -->
    <div class="postImageArea mt20">
      {{ formset.management_form }}
        {% for file_form in formset %}
          <div class="image_field mt10">
            {{ file_form.label_tag }}
            {{ file_form }}
          </div>
        {% endfor %}
    </div>
    <!-- Additional -->
    <div id="SW_add" class="post_sw mt20">
      <h4>{% trans "Additional" %}<span>&#9660</span></h4>
    </div>
    <div class="add_Z opp_Zone pt10 off">
      <div class="field">
        {{ form.maker.label_tag }}
        {{ form.maker }}
      </div>
      <div class="field">
        {{ form.saved.label_tag }}
        {{ form.saved }}
      </div>
      <div class="field">
        {{ form.explain.label_tag }}
        {{ form.explain }}
      </div>
    </div>
    <!-- acq -->
    <div id="SW_acq" class="post_sw mt20">
      <h4>{% trans "Acquisition" %}<span>&#9660</span></h4>
    </div>
    <div class="acq_Z opp_Zone pt10 off">
      <div class="field acq">
        <label for="id_acq_day">{% trans "Day of acquisition" %}:</label>
        {{ form.acq_day }}
      </div>
      <div class="field acq">
        {{ form.acq_place.label_tag }}
        {{ form.acq_place }}
      </div>
      <div class="field acq">
        <label for="id_price">{% trans "Price" %}:</label>
        {{ form.price }}
      </div>
    </div>
    <input type="hidden" name="next" value="{{ request.GET.next }}">
    <div class="mt20">
      <button class="submitA mla" type="submit">{{ button }}</button>
    </div>
  </form>
</div>
{% endblock %}
{% block js %}
<script src="{% static 'collect/posting.js' %}"></script>
{% endblock %}

collect/templates/collect/the_home.html
{% extends 'collect/base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
  {% if user.is_authenticated %}
  <section class="pbBottom">
    {% include 'collect/search_form.html' %}
    <div class="columnArea">
        <h3 class="Midashi">{{ theme }}</h3>
        {% for collect in collects %}
          <article class="collectList hrefBox{% for tag in collect.tag.all %} {{ tag.text }}_arti{% endfor %} {{ collect.state }}_arti">
            <div class="imageFrame">
              {% if collect.photo_set %}
                <img src="{{ collect.photo_set.first.photo.url }}">
              {% endif %}
            </div>
            <div class="collectinfo">
              <div class="ue">
                <div class="itemName">
                  <h3>{{ collect.name }}</h3>
                </div>
                <div class="itemVisual">
                    {% if collect.state == "NEGOTIABLE" %}
                      <a class="circleV"></a>
                    {% elif collect.state == "THIRSTY" %}
                      <a class="starV">★</a>
                    {% elif collect.state == "NON-NEGOTIABLE" %}
                      <a class="heartV">♥</a>
                    {% else %}
                      <a class="squareV"></a>
                    {% endif %}
                  <div class="itemPrice">
                    <a class="priceV">
                      {% if collect.price %}
                        {{ collect.price }}
                      {% endif %}
                    </a>
                  </div>
                </div>
              </div>
              <div class="shita">
                <div class="hosokuA">
                  <div class="sonotaA">
                        {% if collect.niced %}
                          <i class="far fa-thumbs-up mr15 salmon"></i>
                        {% else %}
                          <i class="far fa-thumbs-up mr15"></i>
                        {% endif %}
                    <span>
                      {{ collect.nice_count }}
                    </span>
                    <i class="far fa-comments mr15 ml20"></i>
                    <span>
                      {{ collect.com_count }}
                    </span>
                  </div>
                  <div class="sonotaA">
                    <span>{{ collect.posted }}</span>
                  </div>
                </div>
                <div class="placeArea">
                  <a class="placeInfo">
                    {% if request.user == collect.user %}
                      {% if collect.place %}
                        {{ collect.place }}
                      {% endif %}
                    {% endif %}
                  </a>
                </div>
              </div>
            </div>
            <a class="hrefBoxIn" href="{% url 'detail' collect.id %}"></a>
          </article>
        {% endfor %}
        {% if collects.count > 0 %}
        <div class="mt20 flex-normal narrowDL">
          <span class="flex-cen w100 pt10 pb10 hrefBox submitFull">
            {% trans "Download csv" %}
          <a class="hrefBoxIn" href="{% url 'download_page' %}"></a>
          </span>
        </div>
        {% endif %}
      <div class="shareZone flex-normal sp_bw mt10">
          <div class="shareWide face hrefBox flex-normal">
            <div class="faceIcon mt8 fa-lg">
              <i class="fab fa-facebook-square"></i>
            </div>
            <div class="flex1 textCen colorW mta mba normalWeight">
              share
            </div>
            <a class="hrefBoxIn" href="https://www.facebook.com/share.php?u={{ request.scheme }}://{{ request.get_host }}/collection/{{ user.username }}" rel="nofollow" target="_blank"></a>
          </div>
          <div class="shareWide twi hrefBox flex-normal">
            <div class="twiIcon h50px">
              <i class="fab fa-twitter fa-lg mt12"></i>
            </div>
            <div class="flex1 textCen colorW mta mba normalWeight">
              share
            </div>
            <a class="hrefBoxIn" href="https://twitter.com/share?url={{ request.scheme }}://{{ request.get_host }}/collection/{{ user.username }}&text={{ user.username }}" rel="nofollow" target="_blank"></a>
          </div>
      </div>
    </div>
  </section>
  {% endif %}
{% endblock %}
{% block topS %}
  {% if user.is_anonymous %}
  <section>
    <div class="tops">
      <div class="topImage"></div>
      <h1>Manage your collection<br>
        with us
      </h1>
      <div class="introButton">
        <span class="hrefBox">
          {% trans "About" %}
          <a href="#middles" class="hrefBoxIn"></a>
        </span>
        <span class="hrefBox">
          {% trans "Examples" %}
          <a href="{% url 'example' %}" class="hrefBoxIn"></a>
        </span>
      </div>
    </div>
    <div id="middles">
      <div class="mb20 introContext">
        <h2 class="textCen mb10 pt20 f40px">Main functions</h2>
        <div class="flex-normal"><i class="fas fa-check mr10 ml10"></i><p>{% trans "Easy-to-see collection list." %}</p><br></div>
        <div class="flex-normal"><i class="fas fa-check mr10 ml10 mba"></i><p>{% trans "You can write various information such as date of purchase, place of purchase, and memories." %}</p></div>
        <div class="flex-normal"><i class="fas fa-check mr10 ml10"></i><p>{% trans "Filtering by tags, location, status and category." %}</p></div>
      </div>
      <div id="introMovie">
        <iframe width="100%" src="https://www.youtube.com/embed/M1V-M5qRbuk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
      <h1 class="textCen mt30 salmon f40px">Let's start!!</h1>
      <div class="mt20 bottoms flex-normal sp-ev">
        <span class="hrefBox">
          Sign in
          <a class="hrefBoxIn" href="{% url 'user:login' %}"></a>
        </span>
        <span class="hrefBox">
          Sign up
          <a class="hrefBoxIn" href="{% url 'user:register' %}"></a>
        </span>
      </div>
    </div>
  </section>
  <style>
    .topImage {
      background: url("{% static 'images/top-image_big2.png' %}") no-repeat center;
    }
    #leftArea, #rightArea, .narrowH, #wrapper {
      display: none;
    }
    @media screen and (max-width: 1199px) {
      .topImage {
        background: url("{% static 'images/top-image.png' %}") no-repeat center;
      }
    }
    @media screen and (max-width: 599px) {
      .topImage {
        background: url("{% static 'images/top-image_small.png' %}") no-repeat center;
      }
    }
  </style>
  {% endif %}
{% endblock %}
{% block js %}
<script>
$(function(){
  $("div .SC_rec").addClass("active");
});
</script>
{% endblock %}