collect/urls.py
from django.urls import path
from . import views
from . import api_view

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    #path('collect/<pk>', views.Detail.as_view(), name='detail'),
    path('collect/<pk>', views.detail, name='detail'),
    path('update/<pk>', views.update, name='update'),
    path('post/', views.add_post, name='post'),
    path('example/', views.ExampleList.as_view(), name='example'),
    path('collection/<username>', views.CollectList.as_view(), name='list'),
    #path('wish', views.WishList.as_view(), name='wish'),
    #path('collection/<username>/wish', views.UserWish.as_view(), name='user_wish'),
    path('category', views.CategoryList.as_view(), name='category'),
    #path('collection/<username>/category', views.UserCategory.as_view(), name='user_category'),
    path('place', views.PlaceList.as_view(), name='place'),
    path('nice', views.NiceList.as_view(), name='nice'),
    path('nice/<collect_pk>', views.NiceUser.as_view(), name='nicer'),
    path('download', views.download_page, name='download_page'),
    path('downloading', views.download, name='download'),
    path('search/', views.search, name='search'),
    # API
    path('category/api', api_view.CategoryAPI.as_view(), name='cat_api'),
    path('category/api/<pk>', api_view.CategoryRetAPI.as_view(), name='cat_api_pk'),
    path('place/api', api_view.PlaceAPI.as_view(), name='place_api'),
    path('place/api/<pk>', api_view.PlaceRetAPI.as_view(), name='place_api_pk'),
    path('post/api', api_view.CollectAPI.as_view(), name='post_api'),
    path('collect/api/<pk>', api_view.CollectRetAPI.as_view(), name='collect_api_pk'),
    path('photo/api', api_view.PhotoAPI.as_view(), name='photo_api'),
    path('collect/<collect_pk>/comment', api_view.CommentAPI.as_view(), name='collect_api'),
    path('collect/<comment_pk>/reply', api_view.ReplyAPI.as_view(), name='reply_api'),
    path('collect/<collect_pk>/nice', api_view.NiceAPI.as_view(), name='nice_api'),
    path('offer/<collect_pk>/', api_view.OfferAPI.as_view(), name='offer_api'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('collect.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('user/', include('user.urls', namespace='user')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import (PasswordReset,
                    PasswordResetDone,
                    PasswordResetConfirm,
                    PasswordResetComplete,
                    UserCreate,
                    UserCreateDone,
                    UserCreateComplete,
                    profile,
                    detail,
                    delete,
                    delete_conf,
                    )
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html',
        next_page='/'), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('delete/<username>', delete, name='user_delete'),
    path('delete/confirm/<username>', delete_conf, name='delete_conf'),
    path('register/', UserCreate.as_view(), name='register'),
    path('register/done/', UserCreateDone.as_view(), name='register_done'),
    path('register/complete/<token>/', UserCreateComplete.as_view(), name='register_complete'),
    path('password/reset/', PasswordReset.as_view(), name='reset'),
    path('password/reset/done/', PasswordResetDone.as_view(), name='reset_done'),
    path('password/reset/confirm/<str:uidb64>/<str:token>/', PasswordResetConfirm.as_view(), name='reset_confirm'),
    path('password/reset/complete/', PasswordResetComplete.as_view(), name='reset_complete'),
    path('profile/', profile, name='profile'),
]

user/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from django.core.mail import send_mail

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, username, name, email, password, **extra_fields):
        """メールアドレスでの登録を必須にする"""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        name = name
        user = self.model(email=email, username=username, name=name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email, name, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, name, email, password, **extra_fields)

    def create_superuser(self, username, name, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, name, email, password, **extra_fields)
    
class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""
    email = models.EmailField(_('email'), unique=True, blank=False, null=False)
    username = models.SlugField(_('username'), max_length=24, unique=True, blank=False, null=False)
    name = models.CharField(_('name'), max_length=24, blank=False, null=False)
    picture = models.ImageField(_('picture'), upload_to='profile/', default='default.png')
    intro = models.TextField(_('introduction'), max_length=400, blank=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('launch'), default=timezone.now)

    objects = UserManager()

    def __str__(self):
        return self.name

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'name']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')


    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

user/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm, AuthenticationForm, PasswordChangeForm,PasswordResetForm,
    SetPasswordForm
)
from .models import User
from django.contrib.auth import get_user_model

User = get_user_model()

class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'name', 'email', 'password1']

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        User.objects.filter(username=username, is_active=False).delete()
        return username

class UserUpdateForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ['name', 'intro']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['picture']

class MyPasswordChangeForm(PasswordChangeForm):
    """パスワード変更フォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class MyPasswordResetForm(PasswordResetForm):
    """パスワード忘れたときのフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MySetPasswordForm(SetPasswordForm):
    """パスワード再設定用フォーム(パスワード忘れて再設定)"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'



user/views.py
from django.shortcuts import render, redirect, resolve_url, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth import login as auth_login
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import Http404, HttpResponseBadRequest
from django.utils.encoding import force_bytes, force_text
from django.views import generic
from django.template.loader import get_template
from django.contrib.auth.views import (
        LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordChangeView, PasswordChangeDoneView,
        PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from .forms import (
    UserUpdateForm, MyPasswordChangeForm,
    MyPasswordResetForm, MySetPasswordForm, UserRegisterForm, UserUpdateForm, ProfileUpdateForm
)
from django.urls import reverse_lazy
from .models import User

class UserCreate(generic.CreateView):
    template_name = 'user/register.html'
    form_class = UserRegisterForm

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        from_email = settings.EMAIL_HOST_USER

        subject_template = get_template('user/mail_template/create/subject.txt')
        subject = subject_template.render(context)

        message_template = get_template('user/mail_template/create/message.txt')
        message = message_template.render(context)

        user.email_user(subject, message)

        return redirect('user:register_done')

class UserCreateDone(generic.TemplateView):
    """ユーザー仮登録したよ"""
    template_name = 'user/user_create_done.html'

class UserCreateComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'user/user_create_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)
    
    def get(self, request, **kwargs):
        token = kwargs.get('token')
 
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()

                    auth_login(request, user)
                    
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()

@login_required
def profile(request):
    if request.method == 'POST':
        uform = UserUpdateForm(request.POST, instance=request.user)
        pform = ProfileUpdateForm(request.POST, request.FILES, instance=request.user)

        if uform.is_valid() and pform.is_valid():
            uform.save()
            pform.save()
            return redirect('home')
    else:
        uform = UserUpdateForm(instance=request.user)
        pform = ProfileUpdateForm(instance=request.user)

    return render(request, 'user/profile.html', {'uform': uform, 'pform': pform})

class PasswordReset(PasswordResetView):
    """パスワード変更用URLの送付ページ"""
    subject_template_name = 'user/mail_template/password_reset/subject.txt'
    email_template_name = 'user/mail_template/password_reset/message.txt'
    template_name = 'user/password_reset.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('user:reset_done')


class PasswordResetDone(PasswordResetDoneView):
    """パスワード変更用URLを送りましたページ"""
    template_name = 'user/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力ページ"""
    form_class = MySetPasswordForm
    success_url = reverse_lazy('user:reset_complete')
    template_name = 'user/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    """新パスワード設定しましたページ"""
    template_name = 'user/password_reset_complete.html'

class PasswordChange(PasswordChangeView):
    """パスワード変更ビュー"""
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('user:change_done')
    template_name = 'user/password_change.html'


class PasswordChangeDone(PasswordChangeDoneView):
    """パスワード変更しました"""
    template_name = 'user/password_change_done.html'

def detail(request, username):
    user = get_object_or_404(User, username=username)
    context = {
        'user': user,
    }
    return render(request, 'user/user_detail.html', context)

@login_required
def delete(request, username):
    user = get_object_or_404(User, username=username)
    #user = request.user
    User.objects.filter(username=user.username).delete()
    return redirect('home')

@login_required
def delete_conf(request, username):
    user = get_object_or_404(User, username=username)
    return render(request, 'user/user_delete.html')

user/templates/user/login.html
{% extends "collect/base.html" %}
{% load i18n %}
{% block title %}
{% trans "Login" %}
{% endblock %}
{% block content %}
<div class="per60">
  <div class="pl11">
    <form method="POST">
      {% csrf_token %}
      <h3>Login</h3>
        {{ form.non_field_errors }}
        <div class="field">
          <label for="id_username">{% trans "Email or Username" %}:</label><br>
          {{ form.username }}
          {% if form.username.errors %}
            {{ form.username.error }}
          {% endif %}
        </div>
        <div class="field">
          {{ form.password.label_tag }}<br>
          {{ form.password }}
          {% if form.password.errors %}
            {{ form.password.error }}
          {% endif %}
        </div>
        <input type="hidden" name="next" value="{{ request.GET.next }}">
      <div class="mt20">
        <a class="a_under" href="{% url 'user:reset' %}">{% trans "If you forget password." %}</a>
      </div>
      <div class="mt10">
        <button class="submitFull pt10 pb10 w100" type="submit">{% trans "Login" %}</button>
      </div>
    </form>
    <h4 class="mt20" style="text-align: center;">---- {% trans "Registration" %} ----</h4>
    <div class="mt10 w100">
      <button class="submitFull pt10 pb10 w100 hrefBox">
        {% trans "Sign up" %}
        <a class="hrefBoxIn"  href="{% url 'user:register' %}"></a>
      </button>
    </div>
  </div>
</div>
{% endblock content %}

user/templates/user/logout.html
{% extends "collect/base.html" %}
{% block content %}
    <h3 class="black-important">You've been logged out</h3>
    <div class="">
        <small class="text-muted">
            Login again?<a class="" href="{% url 'user:login' %}">Login</a>
        </small>
    </div>
{% endblock content %}

user/templates/user/password_change.html
{% extends "collect/base.html" %}
{% load i18n %}
{% block title %}{% trans "Password Change" %}{% endblock %}
{% block content %}
<form action="" method="POST" class="">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="">{% trans "Submit" %}</button>
</form>
{% endblock %}

user/templates/user/password_change_done.html
{% extends "collect/base.html" %}
{% load i18n %}
{% block title %}{% trans "Password Change" %}{% endblock %}
{% block content %}
<p>
    {% trans "Changing password has done." %}<br>
    <a class="" href="{% url 'user:login' %}">{% trans "Login" %}</a>
</p>
{% endblock %}

user/templates/user/password_reset_complete.html
{% extends "collect/base.html" %}
{% load i18n %}
{% block title %}{% trans "Password reset" %}{% endblock %}
{% block content %}
<div class="per60">
<p class="textCen mt25">
    {% trans "You have completed password reset." %}
</p>
<div class="w100 flex-normal">
  <a href="{% url 'user:login' %}" class="submitC w100 pt10 pb10 mt20">{% trans "Login" %}</a>
</div>
</div>
{% endblock %}

user/templates/user/profile.html
{% extends "collect/base.html" %}
{% load static %}
{% load i18n %}
{% block title %}{% trans "Profile" %}{% endblock %}
{% block content %}
<form class="" method="POST" enctype="multipart/form-data">
    <h3>
        {% trans "Change profile" %}
    </h3>
    <div class="mt10 per60">
      {% csrf_token %}
      <div class="field">
        {{ uform.name.label_tag }}<br>
        {{ uform.name }}<br>
      </div>
      <div class="field">
        {{ pform.picture.label_tag }}<br>
        {{ pform.picture }}
      </div>
      <div class="field">
    {{ uform.intro.label_tag }}<br>
          {{ uform.intro }}
      </div>
      <div class="form-group flex-normal">
        <button class="submitFull pt10 pb10 flex-cen w100" type="submit">{% trans "Change" %}</button>
      </div>
    </div>
</form>
<div class="mt20">
  <h3>
    {% trans "Logout" %}
  </h3>
  <div class="flex-normal">
    <span class="LOBtn submitFull pt10 pb10 flex-cen w100 mt5">{% trans "Logout" %}</span>
  </div>
  <div class="modal off"></div>
  <div class="modal-con off">
    <div>
      <h3 style="text-align: center;">{% trans "Logout" %}?</h3>
    </div>
    <div class="mt25 flex-normal">
      <a class="cancelBtn flex-cen w50 h50px"><b>{% trans "Cancel" %}</b></a>
      <a class="DelColl submitC flex-cen w50 h50px" href="{% url 'user:logout' %}"><b>{% trans "Logout" %}</b></a>
    </div>
  </div>
</div>
<div class="mt20">
  <h3>{% trans "Withdrawal" %}</h3>
  <div class="flex-normal">
    <a class="submitFull pt10 pb10 flex-cen w100 mt5" href="{% url 'user:delete_conf' user.username %}">{% trans "Withdrawal" %}</a>
  </div>
</div>
{% endblock content %}
{% block js %}
<script src="{% static 'collect/profile.js' %}"></script>
{% endblock %}

user/templates/user/register.html
{% extends "collect/base.html" %}
{% load i18n %}
{% block title %}{% trans "Registration" %}{% endblock %}
{% block content %}
<div class="per60 pl11">
  <h3>{% trans "Sign up" %}</h3>
    <div class="mt10">
      <form method="POST" action="">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="field">
          {{ form.username.label_tag }}<br>
          {{ form.username }}
          {% if form.username.errors %}
            {{ form.username.error }}
          {% endif %}
        </div>
        <div class="field">
            {{ form.name.label_tag }}<br>
            {{ form.name }}
            {% if form.name.errors %}
              {{ form.name.error }}
            {% endif %}
        </div>
        <div class="field">
            {{ form.email.label_tag }}<br>
            {{ form.email }}
            {% if form.email.errors %}
              {{ form.email.error }}
            {% endif %}
        </div>
        <div class="field">
            {{ form.password1.label_tag }}<br>
            {{ form.password1 }}
            {% if form.password1.errors %}
              {{ form.password1.error }}
            {% endif %}
        </div>
        <div class="field">
            {{ form.password2.label_tag }}<br>
            {{ form.password2 }}
            {% if form.password2.errors %}
              {{ form.password2.error }}
            {% endif %}
        </div>
        <div class="mt10 kiyaku">
          <input id="kiyakuInput" class="mr20" type="checkbox" value="">{% trans "I accept and agree to the " %}<a>{% trans "Terms of Use." %}</a>
        </div>
        <div class="modalR off"></div>
        <div class="modalR-con off">
          <div class="modal-title">
            <h2>{% trans "Terms of Use" %}<span class="floatR closeBtn">×</span></h2>
          </div>
          <div class="modal-contents">
            <div>
              <h3>{% trans "User Registration" %}</h3>
              <p>{% trans "You agree to keep your password confidential and will be responsible for all use of your account and password. We reserve the right to remove, reclaim, or change a username you select if we determine, in our sole discretion, that such username and name is inappropriate, obscene, or otherwise objectionable." %}</p>
              <h3>{% trans "Changing Terms of Use" %}</h3>
              <p>{% trans "If deemed necessary, we may change this agreement at any time without notifying the user. If you start using this service after changing these Terms, it is assumed that the user has agreed to the changed Terms." %}</p>          
              <h3>{% trans "Prohibited Activities" %}</h3>
              <p>{% trans "As a user of the Site, you agree not to" %}:</p>
              <ol>
                <li>{% trans "Systematically retrieve data or other content from the Site to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us." %}</li>
                <li>{% trans "Make any unauthorized use of the Site, including collecting usernames and/or email addresses of users by electronic or other means for the purpose of Sending unsolicited email, or creating user accounts by automated means or under false pretenses." %}</li>
                <li>{% trans "Use a buying agent or purchasing agent to make purchases on the Site." %}</li>
                <li>{% trans "Circumvent, disable, or otherwise interfere with security-related features of the Site, including features that prevent or restrict the use or copying of any Content or enforce limitations on the use of the Site and/or the Content contained therein." %}</li>
                <li>{% trans "Engage in unauthorized framing of or linking to the Site." %}</li>
                <li>{% trans "Trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords" %};</li>
                <li>{% trans "Make improper use of our support services or submit false reports of abuse or misconduct." %}</li>
                <li>{% trans "Engage in any automated use of the system, such as using scripts to send comments or messages, or using any data mining, robots, or similar data gathering and extraction tools." %}</li>
                <li>{% trans "Interfere with, disrupt, or create an undue burden on the Site or the networks or services connected to the Site." %}</li>
                <li>{% trans "Attempt to impersonate another user or person or use the username of another user." %}</li>
                <li>{% trans "Sell or otherwise transfer your profile." %}</li>
                <li>{% trans "Use any information obtained from the Site in order to harass, abuse, or harm another person." %}</li>
                <li>{% trans "Use the Site as part of any effort to compete with us or otherwise use the Site and/or the Content for any revenue-generating endeavor or commercial enterprise." %}</li>
                <li>{% trans "Decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the Site." %}</li>
                <li>{% trans "Attempt to bypass any measures of the Site designed to prevent or restrict access to the Site, or any portion of the Site." %}</li>
                <li>{% trans "Harass, annoy, intimidate, or threaten any of our employees or agents engaged in providing any portion of the Site to you." %}</li>
                <li>{% trans "Copy or adapt the Site’s software, including but not limited to Python, HTML, JavaScript, or other code." %}</li>
                <li>{% trans "Upload or transmit (or attempt to upload or to transmit) viruses, Trojan horses, or other material, including excessive use of capital letters and Spamming (continuous posting of repetitive text), that interferes with any party’s uninterrupted use and enjoyment of the Site or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operation, or maintenance of the Site." %}</li>
                <li>{% trans "Except as may be the result of standard search engine or Internet browser usage, use, launch, develop, or distribute any automated system, including without limitation, any spider, robot, cheat utility, scraper, or offline reader that accesses the Site, or using or launching any unauthorized script or other software." %}</li>
                <li>{% trans "Disparage, tarnish, or otherwise harm, in our opinion, us and/or the Site." %}</li>
                <li>{% trans "Use the Site in a manner inconsistent with any applicable laws or regulations." %}</li>
              </ol>
              <h3>{% trans "Guidelines for posting" %}</h3>
              <p>{% trans "If a user violate any of these Terms, we can delete the posted data, restrict the use of the service, and delete the user's registration without prior notice." %}<br><br>
                {% trans "The posting rules are as follows." %}</p>
              <ol>
                <li>{% trans "Your posts should not contain offensive profanity, or abusive, racist, offensive, or hate language" %};</li>
                <li>{% trans "Your posts should not contain discriminatory references based on religion, race, gender, national origin, age, marital status, sexual orientation, or disability" %};</li>
                <li>{% trans "Your posts should not contain references to illegal activity" %};</li>
                <li>{% trans "You may not post any false or misleading statements" %};</li>
                <li>{% trans "You may not organize a campaign encouraging others to post, whether positive or negative." %}</li>
                <li>{% trans "We may accept, reject, or remove posts in our sole discretion. We have absolutely no obligation to screen posts or to delete posts, even if anyone considers posts objectionable or inaccurate. Posts are not endorsed by us, and do not necessarily represent our opinions or the views of any of our affiliates or partners." %}</li>
              </ol>
              <h3>{% trans "Privacy policy" %}</h3>
              <p>{% trans "To reflect in the recommendation, get the action log." %}<br>
                {% trans "User information will not be provided to third parties or used maliciously." %}
              </p>
            </div>
          </div>
        </div>
        <div class="mt20">
          <button disabled class="pt10 pb10 w100 submitFull" id="regiSub" type="submit">{% trans "Register" %}</button>
        </div>
      </form>
      <h4 class="mt20" style="text-align: center;">---- {% trans "Login" %} ----</h4>
      <div class="mt10">
        <button class="pt10 pb10 w100 submitFull hrefBox">
          {% trans "Login" %}
          <a href="{% url 'user:login' %}" class="hrefBoxIn"></a>
        </button>
      </div>
    </div>
</div>
{% endblock content %}

user/templates/user/user_delete.html
{% extends 'collect/base.html' %}
{% load i18n %}
{% block title %}{% trans "Withdraw" %}{% endblock %}
{% block content %}
<h3 class="pl11">Withdrawal</h3>
<div class="mt10 per60 pl11">
  <p>{% trans "Your collection and your user data is completely deleted." %}<br>
     {% trans "Are you sure to withdraw?" %}
  </p>
  <div class="flex-normal mt10">
    <a class="sakujoU submitFull pt5 pb5 flex-cen w100" >{% trans "Withdrawal" %}</a>
  </div>
  <div class="modal off"></div>
  <div class="modal-con off">
    <div>
      <h3 style="text-align: center;">{% trans "Are you sure?" %}</h3>
    </div>
    <div class="mt25 flex-normal">
      <a class="cancelBtnU flex-cen w50 h50px"><b>{% trans "Cancel" %}</b></a>
      <a href="{% url 'user:user_delete' user.username %}" class="submitC flex-cen w50 h50px"><b>{% trans "Delete" %}</b></a>
    </div>
  </div>
</div>
{% endblock %}

user/templates/user/user_detail.html
{% extends "collect/base.html" %}
{% load static %}
{% load i18n %}
{% block title %}{{ user.name }}{% endblock %}

{% block content %}
<div class="columnArea">
  <div class="per60 pl11">
    <div class="OZI hrefBox">
      <div class="ownerImageBack"></div>
      <div class="ownerNameZone">
          <h4>{{ user.name }}</h4>
      </div>
      <a href="{% url 'user:detail' user.username %}" class="hrefBoxIn"></a>
    </div>
    <div class="mt10">
      <h4>Username: {{ user.username }}</h4>
    </div>
    <div class="mt5">
      <p>{{ user.intro }}</p>
    </div>
  </div>
</div>
<style>
  .ownerImageBack {
      background-image: url("{{ user.picture.url }}");
      width: 60px;
      height: 60px;
      border-radius: 50%;
      background-position: center;
  }
  </style>
{% endblock %}